# Generated by Django 4.1.3 on 2022-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
